server.port=${SERVER_PORT:8085}
frontend.host-url=${FRONTEND_HOST_URL:http://localhost:3000}
spring.mail.username=staymatetest@gmail.com
spring.mail.password=lxkukatuusgrvdmt
eureka.client.service-url.defaultZone=http://discovery-service.staymate.local:8761/eureka/
