spring.application.name=booking-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

user.service.name=${USER_SERVICE_NAME:user-service}
room.service.name=${ROOM_SERVICE_NAME:hotel-service}
notification.service.name=${NOTIFICATION_SERVICE_NAME:notification-service}

