server.port=${SERVER_PORT:8081}
spring.datasource.url=jdbc:mysql://staymate-rds.c3geuwcoi6en.ap-southeast-1.rds.amazonaws.com:3306/StayMate_User?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=staymate_user
spring.datasource.password=password
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
email.service.name=email-service.${SERVICE_CONNECT_NAMESPACE:staymate}:8085
hotel.service.name=hotel-service.${SERVICE_CONNECT_NAMESPACE:staymate}:8082
