server.port=${SERVER_PORT:8083}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
