server.port=${SERVER_PORT:8086}
spring.datasource.url=jdbc:mysql://staymate-rds.c3geuwcoi6en.ap-southeast-1.rds.amazonaws.com:3306/StayMate_Payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=staymate_user
spring.datasource.password=password
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
booking.service.name=booking-service.${SERVICE_CONNECT_NAMESPACE:staymate}:8084
notification.service.name=notification-service.${SERVICE_CONNECT_NAMESPACE:staymate}:8083
