export const OPEN_CAGE_API_KEY = import.meta.env.VITE_APP_OPEN_CAGE_API_KEY;

const API_GATEWAY_BASE_URL =
  import.meta.env.VITE_APP_API_GATEWAY_BASE_URL ?? "http://localhost:8080/api";

export const USER_BASE_URL = API_GATEWAY_BASE_URL;
export const HOTEL_BASE_URL = API_GATEWAY_BASE_URL;
export const BOOKING_BASE_URL = API_GATEWAY_BASE_URL;
export const NOTIFICATION_BASE_URL = API_GATEWAY_BASE_URL;
export const PAYMENT_BASE_URL = API_GATEWAY_BASE_URL;
