name: Deploy Frontend to S3

on:
  push:
    branches:
      - main
      - feature/zk-develop
    paths:
      - "frontend/hotel-booking-frontend/**"
      - ".github/workflows/deploy-frontend-pages.yml"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "frontend/hotel-booking-frontend/package-lock.json"

      - name: Install dependencies
        working-directory: frontend/hotel-booking-frontend
        run: npm ci

      - name: Build
        working-directory: frontend/hotel-booking-frontend
        env:
          VITE_APP_API_GATEWAY_BASE_URL: ${{ vars.VITE_APP_API_GATEWAY_BASE_URL }}
          VITE_APP_OPEN_CAGE_API_KEY: ${{ vars.VITE_APP_OPEN_CAGE_API_KEY }}
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::241533158848:role/GitHubActionsECRPushRole
          aws-region: ap-southeast-1

      - name: Sync to S3
        run: |
          aws s3 sync frontend/hotel-booking-frontend/dist s3://www.staymate.org --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1ANYJ00XJRQL6 \
            --paths "/*"
